### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by adomas-sk** [samakintunde/url-sh#1]
-  [This should say that the server did not shut down gracefully](https://github.com/samakintunde/url-sh/blob/main/main.go#L56-L58)
- [I'm guessing that this is WIP, but you should probably also copy web build in here?](https://github.com/samakintunde/url-sh/blob/main/Dockerfile#L22-L23)
- Also move go files to a separate directory (why is `web.go` in `web` directory, while everything else is in root?)

**Comment by samakintunde** [comment]
1. That's pretty much the same. There was an `error shutting down server gracefully`.
2. So Go has this nice thing where you can embed the assets into the binary itself - [web.go](https://github.com/samakintunde/url-sh/blob/02789a0d6b16b922342e75d65a8ceda3b9917b40/web.go#L10)
3. I was trying to have the `web.go` in its own package but it probably makes sense to have it apart from the web assets.
